url: https://submergestl.com
baseurl: ''

# Site settings
title: Submerge
email: admissions@stlchristian.edu
description: "An event designed to submerge High Schoolers DEEPER into COLLEGE//CITY//CHRIST."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 27ae60
  secondary: bdc3c7
  secondary-dark: 7f8c8d

# Team names, titles and social links
people:
- name: LOVEtheLOU
  pic: 1
  position: Service
  social:
    - title: twitter
      url: http://twitter.com/LOVE_the_LOU
    - title: facebook
      url: http://facebook.com/LOVEtheLOU

- name: Kiaira Howard
  pic: 2
  position: Worship Pastor, Lighthouse Church
  social:
    - title: twitter
      url: https://twitter.com/KiairaHoward
    - title: facebook
      url: https://www.facebook.com/khoward456

- name: Jeremiah Howze
  pic: 3
  position: Youth Pastor, Gateway Christian Church
  social:
    - title: twitter
      url: https://twitter.com/JeremiahHowze
    - title: facebook
      url: https://www.facebook.com/jerry.howze
      ignore: true

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://facebook.com/stlchristian
  - title: twitter
    url: http://twitter.com/stlchristian
  - title: google-plus
    url: http://plus.google.com/107642261577376969754
  - title: github
    url: http://github.com/stlchristian

# Postal address (add as many lines as necessary)
address:
  - line: 1360 Grandview Dr.
  - line: Florissant, MO 63033

# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]
